apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: ${YOUR_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-proxy-svc
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-proxy-deployment
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: ingress-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-proxy
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-proxy-svc
  namespace: ingress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: ingress-proxy